# Project Name
TARGET = PatchLhowon

# Sources
CPP_SOURCES = Lhowon.cpp

DEBUG=1

# Library Locations
LIBDAISY_DIR = ../libDaisy
DAISYSP_DIR = ../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
