# Project Name
TARGET = ScratchVersio

# Sources
CPP_SOURCES = ScratchVersio.cpp
C_INCLUDES = -I../Common/

DEBUG=1

# Library Locations
LIBDAISY_DIR = ../libDaisy
DAISYSP_DIR = ../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
