name: Build all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  vcvrack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build plugin
      run: make -C Rack/ all

  versio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: Cache libDaisy build
      uses: actions/cache@v2
      with:
        path: ./libDaisy/build
        key: ${{ runner.os }}-libDaisy
    - name: Cache DaisySP build
      uses: actions/cache@v2
      with:
        path: ./DaisySP/build
        key: ${{ runner.os }}-DaisySP
    - name: Build libDaisy
      run: make -C libDaisy
    - name: Build DaisySP
      run: make -C DaisySP
    - name: Build Lhowon
      run: make -C Versio/Lhowon
