# Project Name
TARGET = LhowonVersio

# Sources
CPP_SOURCES = LhowonVersio.cpp
C_INCLUDES = -I../../Common/

DEBUG=1

# Library Locations
LIBDAISY_DIR = ../../Vendor/libDaisy
DAISYSP_DIR = ../../Vendor/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
